name: Sync index.md(in unlisted branch) with README.md(in main branch)

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  sync-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with all branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history so we can access all branches

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout unlisted branch
        run: git checkout unlisted

      - name: Sync docfx/index.md in unlisted with README.md in main
        run: |
          # Checkout README.md from main branch
          git checkout origin/main -- README.md
          
          # move the contents to index.md
          mv README.md docfx/index.md

          # Remove README.md from index if it exists
          git rm --cached README.md || true

          # Stage the changes
          git add docfx/index.md

          # Commit the changes, even if there are no actual file changes
          git commit -m "Sync index.md(unlisted branch) with README.md(main branch)" || echo "No changes to commit"

          # Push the changes
          git push origin unlisted
