name: Sync index.md to README.md in main

on:
  push:
    branches:
      - unlisted
    paths:
      - 'docfx/index.md'

  # Allows you to run this workflow manually from the Actions tab	
  workflow_dispatch:

jobs:
  sync-index:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

     # Configure Git
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      # Fetch the latest main branch
      - name: Fetch latest main branch
        run: git fetch origin main

      # Checkout the main branch
      - name: Checkout main branch
        run: git checkout main

      # Copy index.md from unlisted, rename to README.md, and remove original
      - name: Sync docfx/index.md to README.md in main
        run: |
          # Checkout the docfx/index.md from unlisted branch
          git checkout unlisted -- docfx/index.md
          
          # Rename the file to README.md
          mv docfx/index.md README.md

          # Remove docfx/index.md from the git index
          git rm docfx/index.md

          # Stage the renamed file (README.md)
          git add README.md

          # Commit and push the changes
          git commit -m "Sync docfx/index.md from unlisted to README.md in main"
          git push origin main
